services:
  base:
    environment:
      ConnectionStrings__CoreDbConnection: Host=timeswapdb;Port=5433;Database=TimeSwapApi;Username=${CORE_DB_USER};Password=${CORE_DB_PASSWORD}
      JWTSettings_SecretKey: ${JWT_SECRET}
      JWTSettings_ValidAudience: ${JWT_AUDIENCE}
      JWTSettings_ValidIssuer: ${JWT_ISSUER}
      JWTSettings_ExpiryInSecond: ${JWT_EXPIRY}
      EmailSettings__From: ${EMAIL_FROM}
      EmailSettings__SmtpServer: ${EMAIL_SMTP_SERVER}
      EmailSettings__Port: ${EMAIL_PORT}
      EmailSettings__Username: ${EMAIL_USERNAME}
      EmailSettings__Password: ${EMAIL_PASSWORD}
      Redis__ConnectionString: ${REDIS_CONNECTION}
      Redis__InstanceName: ${REDIS_INSTANCE}
