name: Deploy Timeswap

on:
  workflow_run:
    workflows:
      - "Publish Timeswap Auth Image"
      - "Publish Timeswap API Image"
    types:
      - completed

jobs:
  deploy:
    name:
    runs-on: Linux

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose environment
        run: |
          echo "AUTH_DB_USER=${{ secrets.AUTH_DB_USER }}" >> .env
          echo "AUTH_DB_PASSWORD=${{ secrets.AUTH_DB_PASSWORD }}" >> .env
          echo "CORE_DB_USER=${{ secrets.CORE_DB_USER }}" >> .env
          echo "CORE_DB_PASSWORD=${{ secrets.CORE_DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_ISSUER=${{ secrets.JWT_ISSUER }}" >> .env
          echo "JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}" >> .env
          echo "JWT_EXPIRY=${{ secrets.JWT_EXPIRY }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
          echo "EMAIL_SMTP_SERVER=${{ secrets.EMAIL_SMTP_SERVER }}" >> .env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "REDIS_CONNECTION=${{ secrets.REDIS_CONNECTION }}" >> .env
          echo "REDIS_INSTANCE=${{ secrets.REDIS_INSTANCE }}" >> .env
          echo "PAYOS_CLIENT_ID=${{ secrets.PAYOS_CLIENT_ID }}" >> .env
          echo "PAYOS_API_KEY=${{ secrets.PAYOS_API_KEY }}" >> .env
          echo "PAYOS_CHECKSUM_KEY=${{ secrets.PAYOS_CHECKSUM_KEY }}" >> .env
          echo "PAYOS_RETURN_URL=${{ secrets.PAYOS_RETURN_URL }}" >> .env
          echo "PAYOS_CANCEL_URL=${{ secrets.PAYOS_CANCEL_URL }}" >> .env
          echo "VNPAY_RETURN_URL=${{ secrets.VNPAY_RETURN_URL }}" >> .env
          echo "VNPAY_PAYMENT_URL=${{ secrets.VNPAY_PAYMENT_URL }}" >> .env
          echo "VNPAY_REDIRECT_WEB_URL=${{ secrets.VNPAY_REDIRECT_WEB_URL }}" >> .env
          echo "VNPAY_IPN_URL=${{ secrets.VNPAY_IPN_URL }}" >> .env
          echo "VNPAY_TMN_CODE=${{ secrets.VNPAY_TMN_CODE }}" >> .env
          echo "VNPAY_HASH_SECRET=${{ secrets.VNPAY_HASH_SECRET }}" >> .env
          echo "VNPAY_VERSION=${{ secrets.VNPAY_VERSION }}" >> .env

      - name: Deploy with Docker Compose
        run: |
          docker-compose pull
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up --force-recreate --build -d
          docker image prune -f
