name: Publish Timeswap API Image

on:
  push:
    branches:
      - master
    paths:
      - backend/TimeSwap.Api/**

jobs:
  publish:
    name: Publish Timeswap API Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from .csproj
        id: get_version
        run: |
          chmod +x ./scripts/get-version.sh
          VERSION=$(./scripts/get-version.sh 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Timeswap API Image
        run: |
          cp ./backend/TimeSwap.Api/Dockerfile .
          docker buildx build . \
            --tag ghcr.io/${{ github.repository_owner }}/timeswap-api:${{ steps.get_version.outputs.version }} \
            --tag ghcr.io/${{ github.repository_owner }}/timeswap-api:latest \
            --platform=linux/amd64 \
            --push \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache
